[psql]
  dbname    = "crius"
  host      = "localhost"
  port      = 5432
  user      = "app"
  pass      = "app121"
  blacklist = ["schema_migrations"]
  sslmode   = "disable"

[mysql]
  dbname    = "crius"
  host      = "localhost"
  port      = 3306
  user      = "app"
  pass      = "app121"
  blacklist = ["schema_migrations"]
  sslmode   = "false"
